# Generated by Django 4.1.7 on 2023-08-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribedcompanies',
            old_name='dashboard_displayed',
            new_name='displayed_on_dashboard',
        ),
    ]
