# Generated by Django 4.1.7 on 2023-08-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_dashboard_displayed_subscribedcompanies_displayed_on_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedcompanies',
            name='displayed_on_dashboard',
        ),
    ]
