version: "3.9"
services:
  market_tracker_web:
    build: .
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./market_tracker/media/profile_pics:/market_tracker/media/profile_pics
    depends_on:
      market_db:
        condition: service_healthy

  redis:
    image: redis:7.0-alpine

  market_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=market_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always
    depends_on:
      - celery_app

  celery_app:
    build: .
    command: celery -A api_fetcher.celery_app:celery_obj worker -l info
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=market_tracker.settings

  celery_beat:
    build: .
    command: celery -A api_fetcher.celery_app:celery_obj beat -l info
    depends_on:
      - celery_app