# Generated by Django 4.1.7 on 2023-06-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='Total_vol',
            field=models.TextField(),
        ),
    ]
