# Generated by Django 4.1.7 on 2023-06-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetcher', '0002_alter_stockdata_total_vol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDateAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Stock_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fetcher.stockdata')),
            ],
        ),
    ]
