# Generated by Django 4.1.7 on 2023-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetcher', '0003_stockdateadded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockDateAdded',
            new_name='StockDate',
        ),
    ]
