# Generated by Django 4.1.7 on 2023-06-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetcher', '0004_rename_stockdateadded_stockdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockCom',
            new_name='StockCompanies',
        ),
    ]
