# Generated by Django 4.1.7 on 2023-06-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetcher', '0005_rename_stockcom_stockcompanies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockCompanies',
            new_name='StockCompany',
        ),
    ]
